name: OSV Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 12 * * 1"

permissions:
  contents: read

jobs:
  scan-pr:
    if: github.event_name == 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1  # v2.5.0
    with:
      scan-args: |-
        --lockfile=bun.lock

  scan-repository:
    if: github.event_name != 'pull_request'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1  # v2.5.0
    with:
      scan-args: |-
        --lockfile=bun.lock
